### ISSUE TITLE
Finish the "redis" backend

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-cache#1]
There's one thing to finish:

- In the "redis" backend, invoke http://redis.io/commands/expire, assuming the Model connector is https://github.com/strongloop/loopback-connector-redis.

Please also add some test and send me a pull request.

**Comment by CCharlieLi** [comment]
Hi @makara 
Just to make sure. We need this mixin of redis backend to set TTL for each data that is saved, and automatic remove it  when time's up, right? Well I'm sure the `loopback-connector-redis` has no deployment of EXPIRE for model. I wonder if you have any suggestions?

**Comment by makara** [comment]
> We need this mixin of redis backend to set TTL for each data that is saved

Yes

> and automatic remove it when time's up

Yes but Redis does that automatically

> Well I'm sure the loopback-connector-redis has no deployment of EXPIRE for model

Model doesn't have the method but the connector has. I believe it is `connector.client`. See:

- https://github.com/strongloop/loopback-connector-redis/blob/master/lib/redis.js#L57
- https://github.com/strongloop/loopback-connector-redis/blob/master/lib/redis.js#L169

**Comment by makara** [comment]
Thanks. Closing.

**Comment by makara** [comment]
Please fix the test:

- Rename `CRUD.test.js` to `backend.redis.test.js`.
- Use the `mixins/cacheModel` mixin, not the redis backend directly.
- Fix your code style, for example the indent should be 2 spaces.

**Comment by fraserxu** [comment]
Should I add `standard` to check the code style? It really helps if you don't mind ` ` after `function` keyword :D

**Comment by CCharlieLi** [comment]
@makara Yes, working on it.
@fraserxu Thanks, I think it would be helpful.

**Comment by makara** [comment]
@fraserxu But I mind.. I personally prefer http://jscs.info/

**Comment by fraserxu** [comment]
LOL, then you can use this one and add it to `package.json`

```JSON
{
  "scripts": {
    "benchmarks": "make benchmarks",
    "leak-detection": "make leak-detection",
    "test": "jscs *.js --preset=aribnb && make test"
  }
}
```

**Comment by makara** [comment]
Thanks.
