### ISSUE TITLE
Implementation Setup

### ISSUE THREAD

**Issue by AndersonZacharyT** [Wiredcraft/loopback-cache#40]
Hello!

I'm just a bit confused by the readme as I tried to set this up for testing. 

On the 'setup a model' portion, it says the connector should be redis. I'm using Mongo, but I'm looking for a solution to cache results in Mongo. 

How do I set that up? Do I keep my Mongo persistence, and just add the `loopback-cache` mixin?

Thank you!

**Comment by makara** [comment]
Hi,

Thanks for interested. Unfortunately we don't support MongoDB. However it's very simple to add the support - either in the module or as a plugin, as long as the DB has the expiration feature. Let me put the details in the Readme.

**Comment by makara** [comment]
Done: https://github.com/Wiredcraft/loopback-cache#extending

Let me know if you got further questions. Also you are very welcome to send us a PR if you make it work.

**Comment by xavierchow** [comment]
closing.

**Comment by AndersonZacharyT** [comment]
Thanks guys! :)
