### ISSUE TITLE
Hi How to getting started?

### ISSUE THREAD

**Issue by game-libgdx-unity** [Wiredcraft/loopback-cache#50]
I can't figure out how to use your package to cache my data though.. Is there any tutorial?

Thanks!!

**Comment by game-libgdx-unity** [comment]
For example, if I want to cache user session model, I define a Model named 'Session', using Redis as its datasource, then I add this code to model definition, is that correct?

`# The model JSON
{
  ...
  "mixins": {
    "CacheModel": {
      "backend": "couchbase",
      "ttl": 3600
    }
  },
  ...
}`

**Comment by xavierchow** [comment]
yes, you alos need to add it to model-config.json
```
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins",
      "loopback-cache/mixins"
    ]

```
